<?php
 
 $title = 'Menu Management';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('menu', array('action'=>'create'));?>">Create new menu</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Url</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($menus as $menu) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($menu->menu_name);?></td>     
     <td><?php echo $this->escapeHtml($menu->url);?></td>     
     <td>
         <a href="<?php echo $this->url('menu',
             array('action'=>'edit', 'id' => $menu->menu_id));?>">Edit</a>
         <a href="<?php echo $this->url('menu',
             array('action'=>'delete', 'id' => $menu->menu_id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>